title: errnull
author: errnull
email: errnull@libsvg.com
description: > 
Libsvg's blog.

baseurl: "https://libsvg.org"
permalink: /:year/:month/:day/:title/
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github

github_username: errnull
twitter_username: errnull
instagram_username: errnull
telegram_username: errnull
disqus_shortname: errnull
# Build settings
markdown: kramdown
# theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock